apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: "php"
          image: "dockerimagepath.io"
          ports:
            - name: fastcgi
              containerPort: 9000